# frozen_string_literal: true

require "yaml"
require "digest"

require_relative "manifest/source"
require_relative "manifest/schema_reader"
require_relative "manifest/builder"

module StrongMultiTenant
  module Manifest
    LOCK_HEADER = "# AUTOGENERATED by strong_multi_tenant:build — DO NOT EDIT."

    module_function

    def dump_lock(lock_hash)
      "#{LOCK_HEADER}\n#{YAML.dump(lock_hash)}"
    end

    def load_lock(path)
      raise ConfigurationError, "lock file not found: #{path}" unless File.exist?(path)
      text = File.read(path)
      data = YAML.safe_load(text, permitted_classes: [Symbol], aliases: false) || {}
      unless data.is_a?(Hash)
        raise ConfigurationError, "lock file malformed: #{path}"
      end
      data
    end

    def schema_digest_from_file(schema_path)
      return nil unless schema_path && File.exist?(schema_path)
      Digest::SHA256.hexdigest(File.read(schema_path))
    end
  end
end
